# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lois/Documents/M1ENS/CGDI/CGDI_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lois/Documents/M1ENS/CGDI/CGDI_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lois/Documents/M1ENS/CGDI/CGDI_Project/CMakeFiles /Users/lois/Documents/M1ENS/CGDI/CGDI_Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lois/Documents/M1ENS/CGDI/CGDI_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CGDI_Project

# Build rule for target.
CGDI_Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGDI_Project
.PHONY : CGDI_Project

# fast build rule for target.
CGDI_Project/fast:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/build
.PHONY : CGDI_Project/fast

src/DSS.o: src/DSS.cpp.o

.PHONY : src/DSS.o

# target to build an object file
src/DSS.cpp.o:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/DSS.cpp.o
.PHONY : src/DSS.cpp.o

src/DSS.i: src/DSS.cpp.i

.PHONY : src/DSS.i

# target to preprocess a source file
src/DSS.cpp.i:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/DSS.cpp.i
.PHONY : src/DSS.cpp.i

src/DSS.s: src/DSS.cpp.s

.PHONY : src/DSS.s

# target to generate assembly for a file
src/DSS.cpp.s:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/DSS.cpp.s
.PHONY : src/DSS.cpp.s

src/Histogramme.o: src/Histogramme.cpp.o

.PHONY : src/Histogramme.o

# target to build an object file
src/Histogramme.cpp.o:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Histogramme.cpp.o
.PHONY : src/Histogramme.cpp.o

src/Histogramme.i: src/Histogramme.cpp.i

.PHONY : src/Histogramme.i

# target to preprocess a source file
src/Histogramme.cpp.i:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Histogramme.cpp.i
.PHONY : src/Histogramme.cpp.i

src/Histogramme.s: src/Histogramme.cpp.s

.PHONY : src/Histogramme.s

# target to generate assembly for a file
src/Histogramme.cpp.s:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Histogramme.cpp.s
.PHONY : src/Histogramme.cpp.s

src/Image.o: src/Image.cpp.o

.PHONY : src/Image.o

# target to build an object file
src/Image.cpp.o:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Image.cpp.o
.PHONY : src/Image.cpp.o

src/Image.i: src/Image.cpp.i

.PHONY : src/Image.i

# target to preprocess a source file
src/Image.cpp.i:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Image.cpp.i
.PHONY : src/Image.cpp.i

src/Image.s: src/Image.cpp.s

.PHONY : src/Image.s

# target to generate assembly for a file
src/Image.cpp.s:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Image.cpp.s
.PHONY : src/Image.cpp.s

src/ImageClass.o: src/ImageClass.cpp.o

.PHONY : src/ImageClass.o

# target to build an object file
src/ImageClass.cpp.o:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/ImageClass.cpp.o
.PHONY : src/ImageClass.cpp.o

src/ImageClass.i: src/ImageClass.cpp.i

.PHONY : src/ImageClass.i

# target to preprocess a source file
src/ImageClass.cpp.i:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/ImageClass.cpp.i
.PHONY : src/ImageClass.cpp.i

src/ImageClass.s: src/ImageClass.cpp.s

.PHONY : src/ImageClass.s

# target to generate assembly for a file
src/ImageClass.cpp.s:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/ImageClass.cpp.s
.PHONY : src/ImageClass.cpp.s

src/KNearestNeighbours.o: src/KNearestNeighbours.cpp.o

.PHONY : src/KNearestNeighbours.o

# target to build an object file
src/KNearestNeighbours.cpp.o:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/KNearestNeighbours.cpp.o
.PHONY : src/KNearestNeighbours.cpp.o

src/KNearestNeighbours.i: src/KNearestNeighbours.cpp.i

.PHONY : src/KNearestNeighbours.i

# target to preprocess a source file
src/KNearestNeighbours.cpp.i:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/KNearestNeighbours.cpp.i
.PHONY : src/KNearestNeighbours.cpp.i

src/KNearestNeighbours.s: src/KNearestNeighbours.cpp.s

.PHONY : src/KNearestNeighbours.s

# target to generate assembly for a file
src/KNearestNeighbours.cpp.s:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/KNearestNeighbours.cpp.s
.PHONY : src/KNearestNeighbours.cpp.s

src/Pixel.o: src/Pixel.cpp.o

.PHONY : src/Pixel.o

# target to build an object file
src/Pixel.cpp.o:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Pixel.cpp.o
.PHONY : src/Pixel.cpp.o

src/Pixel.i: src/Pixel.cpp.i

.PHONY : src/Pixel.i

# target to preprocess a source file
src/Pixel.cpp.i:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Pixel.cpp.i
.PHONY : src/Pixel.cpp.i

src/Pixel.s: src/Pixel.cpp.s

.PHONY : src/Pixel.s

# target to generate assembly for a file
src/Pixel.cpp.s:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Pixel.cpp.s
.PHONY : src/Pixel.cpp.s

src/Util.o: src/Util.cpp.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CGDI_Project.dir/build.make CMakeFiles/CGDI_Project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CGDI_Project"
	@echo "... src/DSS.o"
	@echo "... src/DSS.i"
	@echo "... src/DSS.s"
	@echo "... src/Histogramme.o"
	@echo "... src/Histogramme.i"
	@echo "... src/Histogramme.s"
	@echo "... src/Image.o"
	@echo "... src/Image.i"
	@echo "... src/Image.s"
	@echo "... src/ImageClass.o"
	@echo "... src/ImageClass.i"
	@echo "... src/ImageClass.s"
	@echo "... src/KNearestNeighbours.o"
	@echo "... src/KNearestNeighbours.i"
	@echo "... src/KNearestNeighbours.s"
	@echo "... src/Pixel.o"
	@echo "... src/Pixel.i"
	@echo "... src/Pixel.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

